name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...
      
    - name: Run docker
      run: docker-compose up -d

    - name: Test
      run: make run-test

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
